## prepare

In [3]:
## ------- edit params first here --------------

# COSMIC_VER = ['v2','v3']
COSMIC_VER = 'v2'

INPUTROOT = 'export_c3/'
OUTPUTROOT = 'report_c3/'


# utils for os.path
from os.path import join as J
from os.path import exists as E
from os import listdir as L
print('global L,E,J is defined')
import pandas as pd
import numpy as np

#---------------- setup PATHs -------------------
## setup WORKDIR
import os
# Change WORKDIR working directory depend on your projext location
WORKDIR = os.getcwd()

import sys

#---------------- load librarys -------------------

from tqdm.notebook import tqdm

global L,E,J is defined

### Fig2 pre ranked GSEA

In [4]:
import gseapy

In [6]:
ar = pd.read_excel('external_data/AR调控轴基因总结.xlsx', sheet_name = 'Summarize')
ar

,PNAS_2002,Cancer_Cell_2006,JCO_2008,EU_2015,Asangani_AR_signature,Cell_2015,Nature_Med_2016,CCR_2019
0,HPGD,FKBP5,KLK2,STEAP1,ABCC4,KLK3,MPHOSPH9,KLK3
1,PPAP2A,KLK2,ORM1,STEAP2,ABHD2,KLK2,ADAM7,KLK2
2,SCD,ZBTB10,C1orf116,TMPRESS2,ACSL3,PMEPA1,FOLH1,STEAP1
3,SORD,BM039,TMPRSS2,PPAP2A,ADARB2,ABCC4,CD200,STEAP2
4,DHCR24,TMEPAI,TMEPAI,ACSL3,AF349445,NKX3−1,FKBP5,NKX3-1
...,...,...,...,...,...,...,...,...
520,NaN,NaN,SEMA6A,NaN,NaN,NaN,NaN,NaN
521,NaN,NaN,SGPL1,NaN,NaN,NaN,NaN,NaN
522,NaN,NaN,CTBP1,NaN,NaN,NaN,NaN,NaN
523,NaN,NaN,VGLL4,NaN,NaN,NaN,NaN,NaN
524,NaN,NaN,ZNG1F,NaN,NaN,NaN,NaN,NaN

In [7]:
gene_sets = {}
for s in ar.columns:
    genes = ar[s].dropna().to_list()
    gene_sets[s] = genes

In [8]:
gene_sets.keys()

dict_keys(['PNAS_2002', 'Cancer_Cell_2006', 'JCO_2008', 'EU_2015', 'Asangani_AR_signature', 'Cell_2015', 'Nature_Med_2016', 'CCR_2019'])

#### prt

In [21]:
dap = pd.read_excel('report_c3/gsea_input/fig.2C_data_DEG_DAP.xlsx',sheet_name = 'Protein_C1')
dap

,symbol,log2FoldChange,baseMean,t,pvalue,padj,B,stat,abs_log2FC,FC_Ins,median_C1,median_Others
0,GOLPH3,0.589035,-0.050853,10.459526,1.646566e-16,1.224387e-12,26.927709,10.459526,0.589035,True,0.292545,-0.209752
1,CLCN3,0.352553,0.009348,8.546437,8.143314e-13,2.044425e-09,18.799603,8.546437,0.352553,True,0.195358,-0.098453
2,OSBP,0.192768,0.001281,8.543579,8.248082e-13,2.044425e-09,18.787357,8.543579,0.192768,True,0.110609,-0.046972
3,NANS,0.560105,-0.069149,8.471977,1.136155e-12,2.112113e-09,18.480545,8.471977,0.560105,True,0.206425,-0.218468
4,PDXDC1,0.456807,0.005428,8.371301,1.782227e-12,2.650528e-09,18.049167,8.371301,0.456807,True,0.289053,-0.120751
...,...,...,...,...,...,...,...,...,...,...,...,...
7431,EED,0.000108,-0.035901,0.003168,9.974801e-01,9.980169e-01,-6.502117,0.003168,0.000108,True,-0.057276,-0.014086
7432,EIF6,-0.000069,0.029742,-0.002664,9.978813e-01,9.982841e-01,-6.502118,-0.002664,0.000069,False,0.023719,0.020124
7433,ISCA1,-0.000073,0.007733,-0.002085,9.983419e-01,9.986104e-01,-6.502119,-0.002085,0.000073,False,-0.021015,0.000498
7434,PITPNB,0.000041,0.003706,0.001551,9.987662e-01,9.989005e-01,-6.502120,0.001551,0.000041,True,-0.009705,0.000291
7435,THEMIS2,0.000022,-0.012801,0.000440,9.996498e-01,9.996498e-01,-6.502122,0.000440,0.000022,True,-0.055048,-0.014172

In [22]:
ranked_genes_prt = dap.set_index("symbol")['B'].sort_values(ascending=False)
ranked_genes_prt

symbol
GOLPH3     26.927709
CLCN3      18.799603
OSBP       18.787357
NANS       18.480545
PDXDC1     18.049167
             ...
EED        -6.502117
EIF6       -6.502118
ISCA1      -6.502119
PITPNB     -6.502120
THEMIS2    -6.502122
Name: B, Length: 7436, dtype: float64

In [23]:
## this is additional check
## not used in figures
gseapy.prerank(
    rnk=ranked_genes_prt,        # Pre-ranked gene list
    gene_sets=gene_sets,     # Your custom gene set
    outdir='./report_c3/gsea_report/prt_c1/',
    permutation_num=1000,    # Number of permutations for p-value
    min_size=5,              # Minimum genes in a gene set
    max_size=500,            # Maximum genes in a gene set
    format='pdf',           # Output figure format
    seed=42                 # Random seed for reproducibility
)

#### rna

In [30]:
deg = pd.read_excel('report_c3/gsea_input/fig.2C_data_DEG_DAP.xlsx',sheet_name = 'RNAseq_C1')
deg['stat'] = deg['stat'].fillna(0)
deg

,symbol,baseMean,log2FoldChange,abs_log2FC,lfcSE,stat,pvalue,padj
0,POTEE,3973.562705,4.675083,4.675083,0.450797,10.370698,3.370526e-25,6.228732e-21
1,ABCC4,5211.446418,1.754018,1.754018,0.177007,9.909308,3.792639e-23,2.534566e-19
2,PPM1E,129.747991,2.788274,2.788274,0.281611,9.901165,4.114555e-23,2.534566e-19
3,ZNF649,1620.473551,1.598083,1.598083,0.165354,9.664606,4.262569e-22,1.969307e-18
4,ELOVL7,467.224761,1.671150,1.671150,0.177955,9.390855,5.951521e-21,2.199682e-17
...,...,...,...,...,...,...,...,...
19168,ZBED1,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN
19169,ZBTB9,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN
19170,ZNF577,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN
19171,ZNF727,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN
19172,ZNF883,0.000000,NaN,NaN,NaN,0.000000,NaN,NaN

In [31]:
ranked_genes_rna = deg.set_index("symbol")['stat'].sort_values(ascending=False)
ranked_genes_rna

symbol
POTEE      10.370698
ABCC4       9.909308
PPM1E       9.901165
ZNF649      9.664606
ELOVL7      9.390855
             ...
PLCD3      -6.646758
CAPN12     -6.776064
SLC27A3    -6.896566
NYNRIN     -7.193667
STARD5     -7.293497
Name: stat, Length: 19173, dtype: float64

In [33]:
## this is Fig.2C used
gseapy.prerank(
    rnk=ranked_genes_rna,        # Pre-ranked gene list
    gene_sets=gene_sets,     # Your custom gene set
    outdir='./report_c3/gsea_report/rna_c1/',
    permutation_num=1000,    # Number of permutations for p-value
    min_size=5,              # Minimum genes in a gene set
    max_size=500,            # Maximum genes in a gene set
    format='pdf',           # Output figure format
    seed=42                 # Random seed for reproducibility
)

## Fig S4G S4H S4I

In [38]:
# HALLMARK SET 
hm_set = 'external_data/h.all.v7.5.symbols.gmt'

In [39]:
## this is additional check
## not used in figures
gseapy.prerank(
    rnk=ranked_genes_prt,        # Pre-ranked gene list
    gene_sets=hm_set,     # Your custom gene set
    outdir='./report_c3/gsea_report/prt_c1_hm/',
    permutation_num=1000,    # Number of permutations for p-value
    min_size=5,              # Minimum genes in a gene set
    max_size=500,            # Maximum genes in a gene set
    format='pdf',           # Output figure format
    seed=42                 # Random seed for reproducibility
)

In [40]:
## this is Fig S4G S4H S4I used GSEA enrichment plot
gseapy.prerank(
    rnk=ranked_genes_rna,        # Pre-ranked gene list
    gene_sets=hm_set,     # Your custom gene set
    outdir='./report_c3/gsea_report/rna_c1_hm/',
    permutation_num=1000,    # Number of permutations for p-value
    min_size=5,              # Minimum genes in a gene set
    max_size=500,            # Maximum genes in a gene set
    format='pdf',           # Output figure format
    seed=42                 # Random seed for reproducibility
)

## Fig3 corelation